version: '3'
services:
  api:
    container_name: flask-api
    build: .
    ports:
      - "4001:80"
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=False
networks:
    default:
        name: web_framework
        external: true